namespace kasthack.noscope.Tests.Scopes;

using kasthack.noscope.Tests.TestTypes;

/// <summary>
/// Manual implementation of GeneratedAccessorScope for testing.
/// In production, this would be generated by the source generator with compile-time accessors.
/// </summary>
public partial class GeneratedAccessorScope : IGeneratedAccessorScope
{
    private readonly GodObject _target;

    // Static accessors that would normally be generated in the target's NoScopeAccessors class
    private static readonly Accessor<GodObject, int> _accessorPrivateField = Accessor.ForField<GodObject, int>("_privateField");
    private static readonly Accessor<GodObject, string> _accessorPrivateString = Accessor.ForField<GodObject, string>("_privateString");
    private static readonly Accessor<GodObject, int> _accessorReadonlyPrivateField = Accessor.ForField<GodObject, int>("_readonlyPrivateField");

    public GeneratedAccessorScope(GodObject target)
    {
        _target = target;
    }

    public GodObject Target => _target;

    public int _privateField
    {
        get => _accessorPrivateField.Get(Target);
        set => _accessorPrivateField.Set(Target, value);
    }

    public string _privateString
    {
        get => _accessorPrivateString.Get(Target);
        set => _accessorPrivateString.Set(Target, value);
    }

    public int _readonlyPrivateField => _accessorReadonlyPrivateField.Get(Target);
}
