<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Source generator for kasthack.noscope scope facade library</Description>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <DevelopmentDependency>true</DevelopmentDependency>
        <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
        <PackageReference Include="PolySharp" PrivateAssets="all" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\kasthack.noscope.Infra\kasthack.noscope.Infra.csproj" PrivateAssets="all" GeneratePathProperty="true" />
    </ItemGroup>
    <PropertyGroup>
        <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
    </PropertyGroup>
    <Target Name="GetDependencyTargetPaths">
        <ItemGroup>
            <TargetPathWithTargetPlatformMoniker Include="$(OutputPath)\kasthack.noscope.Infra.dll" IncludeRuntimeDependency="false" />
        </ItemGroup>
    </Target>
</Project>